#sonar.projectKey=GC-Bank
#sonar.projectName=GC-Bank
#sonar.java.binaries=.

# sonar-project.properties

sonar.projectKey=GC-Bank
sonar.projectName=GC-Bank

# Mandatory for SonarCloud
sonar.organization=devendraappa

# Recommended settings for Maven Java project
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.java.source=17
