apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service:9090
      isDefault: true
      access: proxy
      editable: true
      # ✅ Add Loki for logs
    - name: Loki
      type: loki
      url: http://loki-service.monitoring.svc.cluster.local:3100
      access: proxy
      jsonData:
        maxLines: 1000
        
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'BankApp'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards