variable "project_name"       { type = string }
variable "env"                { type = string }
variable "cluster_name"       { type = string }
variable "region"             { type = string }
variable "cluster_version"    { type = string }
variable "vpc_id"             { type = string }
variable "private_subnet_ids" { type = list(string) }
variable "node_instance_types"{ type = list(string) }
variable "node_min_size"      { type = number }
variable "node_max_size"      { type = number }
variable "node_desired_size"  { type = number }
variable "cluster_role_arn"   { type = string }
variable "node_role_arn"      { type = string }
variable "node_role_name"     { type = string }