name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  deploy_to_kubernetes:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
          -t deva9017/bankapp:${{ github.run_number }} \
          -t deva9017/bankapp:latest .

      - name: Push Docker images
        run: |
          docker push deva9017/bankapp:${{ github.run_number }}
          docker push deva9017/bankapp:latest

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Connect to EKS
        run: |
          aws eks update-kubeconfig \
          --name bankapp-cluster \
          --region ap-south-1

      - name: Create Kubernetes Secret
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
        run: |
          kubectl delete secret mysql-secret --ignore-not-found

          kubectl create secret generic mysql-secret \
          --from-literal=mysql-root-password="$MYSQL_ROOT_PASSWORD" \
          --from-literal=mysql-database="$MYSQL_DATABASE" \
          --from-literal=mysql-username="$MYSQL_USERNAME" \
          --from-literal=spring-datasource-url="$SPRING_DATASOURCE_URL"

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/mysql/
          kubectl apply -f k8s/bankapp/

      - name: Wait for MySQL
        run: |
          kubectl rollout status deployment/mysql --timeout=300s

      - name: Update bankapp image
        run: |
          kubectl set image deployment/bankapp \
          bankapp=deva9017/bankapp:${{ github.run_number }}

      - name: Annotate deployment
        run: |
          kubectl annotate deployment/bankapp \
          kubernetes.io/change-cause="Build:${{ github.run_number }} Commit:${{ github.sha }}" \
          --overwrite

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/bankapp --timeout=600s

      - name: Deployment status
        run: |
          kubectl get pods -o wide
          kubectl get svc
          kubectl get hpa
          kubectl get pvc

      - name: Rollback if failed
        if: failure()
        run: |
          kubectl rollout undo deployment/bankapp
