apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
spec:
  type: ClusterIP
  ports:
  - port: 9104
    targetPort: 9104
  selector:
    app: mysql-exporter